### ISSUE TITLE
Bot not Running - 

### ISSUE THREAD

**Issue by gujwen** [luke30001/storminator#1]
``Hi,

The bot is not running, in heroku logs I am able to see only these

Below is the logs. please let me know what might be the issue 

`2021-10-18T09:34:49.422777+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.427856+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.437413+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.442087+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.452873+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.460430+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.472532+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.484674+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.495068+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.504296+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.518333+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.526922+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.574202+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.590315+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.603179+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.609011+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.638510+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.667393+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.705768+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.711171+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.737559+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.743161+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:49.757338+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.006436+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.013930+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.033385+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.041956+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.049080+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.054237+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.067005+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.077049+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.086161+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.093754+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.102014+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.109098+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.121259+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.222828+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.227984+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.239126+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.244002+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.255860+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.261524+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.272983+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.283364+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.288272+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.293009+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.302489+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.309748+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.319442+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.324177+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.333779+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.339682+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.344340+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.357910+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.367475+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.372369+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.383165+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.387921+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.392476+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.401564+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.406771+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.417947+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.423121+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.435812+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.441919+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.454210+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.460804+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.471111+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.476410+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.486084+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.491332+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.501488+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login
2021-10-18T09:34:50.507587+00:00 app[Runthis.1]: https://app.stormgain.com/#modal_login`

**Comment by blakerview** [comment]
same problem

**Comment by blakerview** [comment]
now i get this
021-11-05T14:45:38.590908+00:00 heroku[Runthis.1]: Starting process with command `python3 m.py`
2021-11-05T14:45:39.161274+00:00 heroku[Runthis.1]: State changed from starting to up
2021-11-05T14:45:40.398965+00:00 app[Runthis.1]: Traceback (most recent call last):
2021-11-05T14:45:40.398981+00:00 app[Runthis.1]: File "/app/m.py", line 14, in <module>
2021-11-05T14:45:40.399087+00:00 app[Runthis.1]: d = uc.Chrome(options=chrome_options)
2021-11-05T14:45:40.399096+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 302, in __init__
2021-11-05T14:45:40.399234+00:00 app[Runthis.1]: super(Chrome, self).__init__(
2021-11-05T14:45:40.399236+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
2021-11-05T14:45:40.399314+00:00 app[Runthis.1]: super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
2021-11-05T14:45:40.399322+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
2021-11-05T14:45:40.399416+00:00 app[Runthis.1]: RemoteWebDriver.__init__(
2021-11-05T14:45:40.399417+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in __init__
2021-11-05T14:45:40.399520+00:00 app[Runthis.1]: self.start_session(capabilities, browser_profile)
2021-11-05T14:45:40.399522+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 577, in start_session
2021-11-05T14:45:40.399689+00:00 app[Runthis.1]: super(Chrome, self).start_session(capabilities, browser_profile)
2021-11-05T14:45:40.399691+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 339, in start_session
2021-11-05T14:45:40.399797+00:00 app[Runthis.1]: response = self.execute(Command.NEW_SESSION, parameters)
2021-11-05T14:45:40.399805+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 400, in execute
2021-11-05T14:45:40.399914+00:00 app[Runthis.1]: self.error_handler.check_response(response)
2021-11-05T14:45:40.399922+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 236, in check_response
2021-11-05T14:45:40.400015+00:00 app[Runthis.1]: raise exception_class(message, screen, stacktrace)
2021-11-05T14:45:40.400052+00:00 app[Runthis.1]: selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:52538
2021-11-05T14:45:40.400052+00:00 app[Runthis.1]: from session not created: This version of ChromeDriver only supports Chrome version 95
2021-11-05T14:45:40.400052+00:00 app[Runthis.1]: Current browser version is 94.0.4606.54
2021-11-05T14:45:40.400052+00:00 app[Runthis.1]: Stacktrace:
2021-11-05T14:45:40.400053+00:00 app[Runthis.1]: #0 0x55dee0a99f93 <unknown>
2021-11-05T14:45:40.400053+00:00 app[Runthis.1]: #1 0x55dee0574908 <unknown>
2021-11-05T14:45:40.400053+00:00 app[Runthis.1]: #2 0x55dee059b67c <unknown>
2021-11-05T14:45:40.400053+00:00 app[Runthis.1]: #3 0x55dee0592e36 <unknown>
2021-11-05T14:45:40.400053+00:00 app[Runthis.1]: #4 0x55dee05cd770 <unknown>
2021-11-05T14:45:40.400053+00:00 app[Runthis.1]: #5 0x55dee05c7973 <unknown>
2021-11-05T14:45:40.400053+00:00 app[Runthis.1]: #6 0x55dee059ddf4 <unknown>
2021-11-05T14:45:40.400054+00:00 app[Runthis.1]: #7 0x55dee059ede5 <unknown>
2021-11-05T14:45:40.400054+00:00 app[Runthis.1]: #8 0x55dee0ac92be <unknown>
2021-11-05T14:45:40.400054+00:00 app[Runthis.1]: #9 0x55dee0adeba0 <unknown>
2021-11-05T14:45:40.400054+00:00 app[Runthis.1]: #10 0x55dee0aca215 <unknown>
2021-11-05T14:45:40.400054+00:00 app[Runthis.1]: #11 0x55dee0adffe8 <unknown>
2021-11-05T14:45:40.400054+00:00 app[Runthis.1]: #12 0x55dee0abe9db <unknown>
2021-11-05T14:45:40.400055+00:00 app[Runthis.1]: #13 0x55dee0afb218 <unknown>
2021-11-05T14:45:40.400055+00:00 app[Runthis.1]: #14 0x55dee0afb398 <unknown>
2021-11-05T14:45:40.400055+00:00 app[Runthis.1]: #15 0x55dee0b166cd <unknown>
2021-11-05T14:45:40.400055+00:00 app[Runthis.1]: #16 0x7f99a4b03609 <unknown>
2021-11-05T14:45:40.400069+00:00 app[Runthis.1]:
2021-11-05T14:45:41.040179+00:00 heroku[Runthis.1]: Process exited with status 1
2021-11-05T14:45:41.140419+00:00 heroku[Runthis.1]: State changed from up to crashed
2021-11-05T14:46:04.046247+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=stormgaindomenicoformica38.herokuapp.com request_id=32469c18-cf51-40de-9435-2c97b23aeb8e fwd="93.40.193.155" dyno= connect= service= status=503 bytes= protocol=https
2021-11-05T14:46:04.451014+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=stormgaindomenicoformica38.herokuapp.com request_id=bb00f5ea-c92d-44dd-8bf9-640d4a93e005 fwd="93.40.193.155" dyno= connect= service= status=503 bytes= protocol=https
^CTerminare il processo batch (S/N)? n

C:\Users\PC-STUDIO>heroku login
 »   Warning: heroku update available from 7.53.0 to 7.59.1.
heroku: Press any key to open up the browser to login or q to exit:
Opening browser to https://cli-auth.heroku.com/auth/cli/browser/b64032fc-54d4-46de-a609-3fa29fb6300f?requestor=SFMyNTY.g2gDbQAAAA05My40MC4xOTMuMTU1bgYAoDKR8HwBYgABUYA.GQFL65RfiRYwUQqh_z4siINyaU2ajZ2qfpHQBlXDL_A
Logging in... done
Logged in as domenicoformica38@gmail.com

C:\Users\PC-STUDIO>heroku logs --tail --app stormg4inbusinesd38
 »   Warning: heroku update available from 7.53.0 to 7.59.1.
 »   Error: Couldn't find that app.
 »
 »   Error ID: not_found

C:\Users\PC-STUDIO>heroku logs --tail --app stormg4inbusinessd38
 »   Warning: heroku update available from 7.53.0 to 7.59.1.
2021-11-05T14:47:54.798381+00:00 app[api]: Scaled to Runthis@1:Free by user domenicoformica38@gmail.com
2021-11-05T14:48:06.094367+00:00 heroku[Runthis.1]: Starting process with command `python3 m.py`
2021-11-05T14:48:06.735614+00:00 heroku[Runthis.1]: State changed from starting to up
2021-11-05T14:48:07.969321+00:00 app[Runthis.1]: Traceback (most recent call last):
2021-11-05T14:48:07.969787+00:00 app[Runthis.1]: File "/app/m.py", line 14, in <module>
2021-11-05T14:48:07.969787+00:00 app[Runthis.1]: d = uc.Chrome(options=chrome_options)
2021-11-05T14:48:07.969787+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 302, in __init__
2021-11-05T14:48:07.969787+00:00 app[Runthis.1]: super(Chrome, self).__init__(
2021-11-05T14:48:07.969788+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
2021-11-05T14:48:07.969788+00:00 app[Runthis.1]: super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
2021-11-05T14:48:07.969789+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
2021-11-05T14:48:07.969812+00:00 app[Runthis.1]: RemoteWebDriver.__init__(
2021-11-05T14:48:07.969814+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in __init__
2021-11-05T14:48:07.969921+00:00 app[Runthis.1]: self.start_session(capabilities, browser_profile)
2021-11-05T14:48:07.969928+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 577, in start_session
2021-11-05T14:48:07.970101+00:00 app[Runthis.1]: super(Chrome, self).start_session(capabilities, browser_profile)
2021-11-05T14:48:07.970108+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 339, in start_session
2021-11-05T14:48:07.970221+00:00 app[Runthis.1]: response = self.execute(Command.NEW_SESSION, parameters)
2021-11-05T14:48:07.970229+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 400, in execute
2021-11-05T14:48:07.970386+00:00 app[Runthis.1]: self.error_handler.check_response(response)
2021-11-05T14:48:07.970396+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 236, in check_response
2021-11-05T14:48:07.970523+00:00 app[Runthis.1]: raise exception_class(message, screen, stacktrace)
2021-11-05T14:48:07.970562+00:00 app[Runthis.1]: selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:33121
2021-11-05T14:48:07.970563+00:00 app[Runthis.1]: from session not created: This version of ChromeDriver only supports Chrome version 95
2021-11-05T14:48:07.970563+00:00 app[Runthis.1]: Current browser version is 94.0.4606.54
2021-11-05T14:48:07.970564+00:00 app[Runthis.1]: Stacktrace:
2021-11-05T14:48:07.970564+00:00 app[Runthis.1]: #0 0x561994b4bf93 <unknown>
2021-11-05T14:48:07.970564+00:00 app[Runthis.1]: #1 0x561994626908 <unknown>
2021-11-05T14:48:07.970564+00:00 app[Runthis.1]: #2 0x56199464d67c <unknown>
2021-11-05T14:48:07.970564+00:00 app[Runthis.1]: #3 0x561994644e36 <unknown>
2021-11-05T14:48:07.970565+00:00 app[Runthis.1]: #4 0x56199467f770 <unknown>
2021-11-05T14:48:07.970565+00:00 app[Runthis.1]: #5 0x561994679973 <unknown>
2021-11-05T14:48:07.970565+00:00 app[Runthis.1]: #6 0x56199464fdf4 <unknown>
2021-11-05T14:48:07.970566+00:00 app[Runthis.1]: #7 0x561994650de5 <unknown>
2021-11-05T14:48:07.970566+00:00 app[Runthis.1]: #8 0x561994b7b2be <unknown>
2021-11-05T14:48:07.970566+00:00 app[Runthis.1]: #9 0x561994b90ba0 <unknown>
2021-11-05T14:48:07.970566+00:00 app[Runthis.1]: #10 0x561994b7c215 <unknown>
2021-11-05T14:48:07.970566+00:00 app[Runthis.1]: #11 0x561994b91fe8 <unknown>
2021-11-05T14:48:07.970567+00:00 app[Runthis.1]: #12 0x561994b709db <unknown>
2021-11-05T14:48:07.970567+00:00 app[Runthis.1]: #13 0x561994bad218 <unknown>
2021-11-05T14:48:07.970567+00:00 app[Runthis.1]: #14 0x561994bad398 <unknown>
2021-11-05T14:48:07.970567+00:00 app[Runthis.1]: #15 0x561994bc86cd <unknown>
2021-11-05T14:48:07.970568+00:00 app[Runthis.1]: #16 0x7f8889902609 <unknown>
2021-11-05T14:48:07.970569+00:00 app[Runthis.1]:
2021-11-05T14:48:08.614378+00:00 heroku[Runthis.1]: Process exited with status 1
2021-11-05T14:48:08.749307+00:00 heroku[Runthis.1]: State changed from up to crashed
2021-11-05T14:48:08.783382+00:00 heroku[Runthis.1]: State changed from crashed to starting
2021-11-05T14:48:19.904276+00:00 heroku[Runthis.1]: Starting process with command `python3 m.py`
2021-11-05T14:48:21.475839+00:00 heroku[Runthis.1]: State changed from starting to up
2021-11-05T14:48:22.648037+00:00 app[Runthis.1]: Traceback (most recent call last):
2021-11-05T14:48:22.648055+00:00 app[Runthis.1]: File "/app/m.py", line 14, in <module>
2021-11-05T14:48:22.648205+00:00 app[Runthis.1]: d = uc.Chrome(options=chrome_options)
2021-11-05T14:48:22.648218+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 302, in __init__
2021-11-05T14:48:22.648448+00:00 app[Runthis.1]: super(Chrome, self).__init__(
2021-11-05T14:48:22.648457+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
2021-11-05T14:48:22.648580+00:00 app[Runthis.1]: super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
2021-11-05T14:48:22.648590+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
2021-11-05T14:48:22.648714+00:00 app[Runthis.1]: RemoteWebDriver.__init__(
2021-11-05T14:48:22.648724+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in __init__
2021-11-05T14:48:22.648891+00:00 app[Runthis.1]: self.start_session(capabilities, browser_profile)
2021-11-05T14:48:22.648901+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 577, in start_session
2021-11-05T14:48:22.649193+00:00 app[Runthis.1]: super(Chrome, self).start_session(capabilities, browser_profile)
2021-11-05T14:48:22.649203+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 339, in start_session
2021-11-05T14:48:22.649399+00:00 app[Runthis.1]: response = self.execute(Command.NEW_SESSION, parameters)
2021-11-05T14:48:22.649408+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 400, in execute
2021-11-05T14:48:22.649608+00:00 app[Runthis.1]: self.error_handler.check_response(response)
2021-11-05T14:48:22.649619+00:00 app[Runthis.1]: File "/app/.heroku/python/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 236, in check_response
2021-11-05T14:48:22.649788+00:00 app[Runthis.1]: raise exception_class(message, screen, stacktrace)
2021-11-05T14:48:22.649839+00:00 app[Runthis.1]: selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:51586
2021-11-05T14:48:22.649840+00:00 app[Runthis.1]: from session not created: This version of ChromeDriver only supports Chrome version 95
2021-11-05T14:48:22.649840+00:00 app[Runthis.1]: Current browser version is 94.0.4606.54
2021-11-05T14:48:22.649841+00:00 app[Runthis.1]: Stacktrace:
2021-11-05T14:48:22.649841+00:00 app[Runthis.1]: #0 0x5592463e4f93 <unknown>
2021-11-05T14:48:22.649841+00:00 app[Runthis.1]: #1 0x559245ebf908 <unknown>
2021-11-05T14:48:22.649841+00:00 app[Runthis.1]: #2 0x559245ee667c <unknown>
2021-11-05T14:48:22.649842+00:00 app[Runthis.1]: #3 0x559245edde36 <unknown>
2021-11-05T14:48:22.649843+00:00 app[Runthis.1]: #4 0x559245f18770 <unknown>
2021-11-05T14:48:22.649843+00:00 app[Runthis.1]: #5 0x559245f12973 <unknown>
2021-11-05T14:48:22.649843+00:00 app[Runthis.1]: #6 0x559245ee8df4 <unknown>
2021-11-05T14:48:22.649843+00:00 app[Runthis.1]: #7 0x559245ee9de5 <unknown>
2021-11-05T14:48:22.649844+00:00 app[Runthis.1]: #8 0x5592464142be <unknown>
2021-11-05T14:48:22.649844+00:00 app[Runthis.1]: #9 0x559246429ba0 <unknown>
2021-11-05T14:48:22.649844+00:00 app[Runthis.1]: #10 0x559246415215 <unknown>
2021-11-05T14:48:22.649844+00:00 app[Runthis.1]: #11 0x55924642afe8 <unknown>
2021-11-05T14:48:22.649845+00:00 app[Runthis.1]: #12 0x5592464099db <unknown>
2021-11-05T14:48:22.649845+00:00 app[Runthis.1]: #13 0x559246446218 <unknown>
2021-11-05T14:48:22.649845+00:00 app[Runthis.1]: #14 0x559246446398 <unknown>
2021-11-05T14:48:22.649845+00:00 app[Runthis.1]: #15 0x5592464616cd <unknown>
2021-11-05T14:48:22.649846+00:00 app[Runthis.1]: #16 0x7f01f1518609 <unknown>
2021-11-05T14:48:22.649847+00:00 app[Runthis.1]:
2021-11-05T14:48:23.318098+00:00 heroku[Runthis.1]: Process exited with status 1
2021-11-05T14:48:23.416910+00:00 heroku[Runthis.1]: State changed from up to crashed
